import "@radix-ui/themes/styles.css";
import './theme.config.css'
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Theme, ThemePanel } from "@radix-ui/themes"
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "./Navbar";
import AuthProvider from "./api/auth/Provider";
import  QueryClientProvider  from "./QueryClientProvider";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en" data-theme="winter"
            className={inter.variable}
        >
            <body className={inter.variable}>
                <QueryClientProvider>
                <AuthProvider>

                    <Theme accentColor="iris" appearance="light" >
                        <Navbar />
                        <main className="p-5">


                            {children}
                            <Toaster richColors position="top-right" />

                        </main>
                        {/* <ThemePanel /> */}
                    </Theme>
                </AuthProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
