import "@radix-ui/themes/styles.css";
import './theme.config.css'
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import {Theme, ThemePanel} from "@radix-ui/themes"
import "./globals.css";
import Navbar from "./Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" data-theme="winter"
      className={inter.variable}
    >
      <body className="min-h-full flex flex-col">
      
        <Theme accentColor="iris" appearance="light" className="flex flex-col min-h-full">
        <Navbar />
        <main >{children}</main>
        <ThemePanel />
        </Theme>
      </body>
    </html>
  );
}
